name: Build GL4ES for Android

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4


    - name: Configure CMake
      run: |
        mkdir -p build
        cmake -B build \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-29 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_TOOLCHAIN=clang
    - name: Build
      run: cmake --build build --target GL --config Release --parallel $(nproc)

    - name: Strip
      run: |
        cd build
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libGL.so.1 -o libGL.so
        

   
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GL4ES
        path: build/libGL.so
